import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider } from "./Context/user.store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} bg-orange-100  h-[100vh] w-full flex justify-center items-center   `}>
        <GlobalContextProvider> {children}</GlobalContextProvider>
      </body>
    </html>
  );
}
